apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: demo-fint-skjema-data-service
spec:
  itemPath: "vaults/aks-alpha-vault/items/aiven-kafka"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: aiven-kafka-certificates
spec:
  itemPath: "vaults/aks-alpha-vault/items/aiven-kafka-certificates"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: fint-skjema-data-service
  name: fint-skjema-data-service
spec:
  ports:
    - port: 8080
  type: ClusterIP
  selector:
    io.kompose.service: fint-skjema-data-service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-fint-skjema-data-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: "fint-flyt-demo.vigoiks.no"
      http:
        paths:
          - path: /api/kodeverk
            pathType: Prefix
            backend:
              service:
                name: fint-skjema-data-service
                port:
                  number: 8080
          - path: /api/sak
            pathType: Prefix
            backend:
              service:
                name: fint-skjema-data-service
                port:
                  number: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: fint-skjema-data-service
  name: fint-skjema-data-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: fint-skjema-data-service
  template:
    metadata:
      labels:
        io.kompose.service: fint-skjema-data-service
    spec:
      restartPolicy: Always
      volumes:
        - name: credentials
          secret:
            secretName: aiven-kafka-certificates
      containers:
        - image: fintlabsacr.azurecr.io/fint-skjema-data-service:dummy
          name: fint-skjema-data-service
          volumeMounts:
            - name: credentials
              mountPath: /credentials
          resources:
            limits:
              memory: "2048Mi"
              cpu: "1"
            requests:
              memory: "512Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: "aiven-kafka"
          env:
            - { name: TZ, value: Europe/Oslo }
            - { name: JAVA_TOOL_OPTIONS, value: '-XX:+ExitOnOutOfMemoryError -Xmx1840M' }
            - { name: logging.level.no.fintlabs.arkiv, value: info }
            - { name: fint.kafka.topic.org-id, value: 'pwf.no' }
            - { name: fint.security.resourceserver.enabled, value: 'false' }