apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: aiven-kafka
spec:
  itemPath: "vaults/aks-alpha-vault/items/aiven-kafka"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: fint-flyt-data-service
  name: fint-flyt-data-service
spec:
  ports:
    - port: 8080
  type: ClusterIP
  selector:
    io.kompose.service: fint-flyt-data-service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-fint-flyt-data-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: "viken-no-skjema.vigoiks.no"
      http:
        paths:
          - path: /api/sak
            pathType: Prefix
            backend:
              service:
                name: fint-flyt-data-service
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-fint-flyt-data-service-internal
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $token $upstream_http_authorization;
      proxy_set_header Authorization $token;
      proxy_pass_header Authorization;
spec:
  rules:
    - host: "viken-no-skjema.vigoiks.no"
      http:
        paths:
          - path: /api/intern/kodeverk
            pathType: Prefix
            backend:
              service:
                name: fint-flyt-data-service
                port:
                  number: 8080
          - path: /api/intern/sakstittel
            pathType: Prefix
            backend:
              service:
                name: fint-flyt-data-service
                port:
                  number: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: fint-flyt-data-service
  name: fint-flyt-data-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: fint-flyt-data-service
  template:
    metadata:
      labels:
        io.kompose.service: fint-flyt-data-service
    spec:
      restartPolicy: Always
      volumes:
        - name: credentials
          secret:
            secretName: aiven-kafka-certificates
      containers:
        - image: fintlabsacr.azurecr.io/fint-flyt-data-service:dummy
          name: fint-flyt-data-service
          volumeMounts:
            - name: credentials
              mountPath: /credentials
          resources:
            limits:
              memory: "2048Mi"
              cpu: "1"
            requests:
              memory: "512Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: aiven-kafka
          env:
            - { name: TZ, value: Europe/Oslo }
            - { name: JAVA_TOOL_OPTIONS, value: '-XX:+ExitOnOutOfMemoryError -Xmx1840M' }
            - { name: logging.level.no.fintlabs.arkiv, value: info }
            - { name: fint.org-id, value: 'viken.no' }
            - { name: fint.flyt.resource-server.security.api.external.enabled, value: 'true' }
            - { name: fint.flyt.resource-server.security.api.external.authorized-client-ids, value: '1' }
            - { name: fint.flyt.resource-server.security.api.internal.enabled, value: 'true' }
            - { name: fint.flyt.resource-server.security.api.internal.authorized-org-ids, value: 'viken.no, vigo.no' }