apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    io.kompose.service: fint-skjema-data-service
  name: fint-skjema-data-service
spec:
  ports:
    - name: "8081"
      port: 8081
  type: LoadBalancer
  selector:
    io.kompose.service: fint-skjema-data-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: fint-skjema-data-service
  name: fint-skjema-data-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: fint-skjema-data-service
  template:
    metadata:
      labels:
        io.kompose.service: fint-skjema-data-service
    spec:
      restartPolicy: Always
      containers:
        #- image: fintlabsacr.azurecr.io/fint-skjema-data-service:build.${BUILD_NUMBER}_${GIT_COMMIT}
        - image: fintlabsacr.azurecr.io/fint-skjema-data-service:build.10_48fc8f8474a97b9ddc5efc5f9c9c5f64350570e6
          name: fint-skjema-data-service
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1"
            requests:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 8081
          env:
            - {name: TZ, value: Europe/Oslo}
            #- {name: JAVA_TOOL_OPTIONS, value: '-XX:+ExitOnOutOfMemoryError -Xmx920M -verbose:gc'}
            - {name: JAVA_TOOL_OPTIONS, value: '-XX:+ExitOnOutOfMemoryError -Xmx920M'}
            - {name: spring.kafka.bootstrap-servers, value: 'kafka-0.kafka-headless.default.svc.cluster.local:9092'}
            - {name: logging.level.no.fintlabs.arkiv, value: info}