apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: viken-no-fint-skjema-data-service
spec:
  itemPath: "vaults/aks-alpha-vault/items/viken-no-fint-skjema-data-service"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: aiven-kafka-certificates
spec:
  itemPath: "vaults/aks-alpha-vault/items/aiven-kafka-certificates"
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    io.kompose.service: fint-skjema-data-service
  name: fint-skjema-data-service
spec:
  ports:
    - name: "8080"
      port: 8080
  type: LoadBalancer
  selector:
    io.kompose.service: fint-skjema-data-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: fint-skjema-data-service
  name: fint-skjema-data-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: fint-skjema-data-service
  template:
    metadata:
      labels:
        io.kompose.service: fint-skjema-data-service
    spec:
      restartPolicy: Always
      volumes:
        - name: credentials
          secret:
            secretName: aiven-kafka-certificates
      containers:
        - image: fintlabsacr.azurecr.io/fint-skjema-data-service:dummy
          name: fint-skjema-data-service
          volumeMounts:
            - name: credentials
              mountPath: /credentials
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1"
            requests:
              memory: "256"
              cpu: "100m"
          ports:
            - containerPort: 8080
          envFrom:
          - secretRef:
              name: "viken-no-fint-skjema-data-service"
          env:
            - {name: TZ, value: Europe/Oslo}
            #- {name: JAVA_TOOL_OPTIONS, value: '-XX:+ExitOnOutOfMemoryError -Xmx920M -verbose:gc'}
            - {name: JAVA_TOOL_OPTIONS, value: '-XX:+ExitOnOutOfMemoryError -Xmx920M'}
            - {name: logging.level.no.fintlabs.arkiv, value: info}