apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: aiven-kafka
spec:
  itemPath: "vaults/aks-pwf-vault/items/aiven-kafka"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: fint-flyt-data-service
  name: fint-flyt-data-service
spec:
  ports:
    - port: 8080
  type: ClusterIP
  selector:
    io.kompose.service: fint-flyt-data-service
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: fint-flyt-data-service
  labels:
    app: fint-flyt-data-service
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`fint-flyt-demo.vigoiks.no`) && PathPrefix(`/api/intern/arkiv`)
      kind: Rule
      services:
        - name: fint-flyt-data-service
          port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: fint-flyt-data-service
  name: fint-flyt-data-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: fint-flyt-data-service
  template:
    metadata:
      labels:
        io.kompose.service: fint-flyt-data-service
    spec:
      restartPolicy: Always
      volumes:
        - name: credentials
          secret:
            secretName: aiven-kafka-certificates
      containers:
        - image: fintlabsacr.azurecr.io/fint-flyt-data-service:dummy
          name: fint-flyt-data-service
          volumeMounts:
            - name: credentials
              mountPath: /credentials
          resources:
            limits:
              memory: "2048Mi"
              cpu: "1"
            requests:
              memory: "512Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: aiven-kafka
          env:
            - { name: TZ, value: Europe/Oslo }
            - { name: JAVA_TOOL_OPTIONS, value: '-XX:+ExitOnOutOfMemoryError -Xmx1840M' }
            - { name: logging.level.no.fintlabs.arkiv, value: info }
            - { name: fint.org-id, value: 'pwf.no' }
            - { name: fint.flyt.resource-server.security.api.external.enabled, value: 'true' }
            - { name: fint.flyt.resource-server.security.api.external.permit-all, value: 'true' }
            - { name: fint.flyt.resource-server.security.api.internal.enabled, value: 'true' }
            - { name: fint.flyt.resource-server.security.api.internal.permit-all, value: 'true' }