fint:
  org-id: fintlabs.no
  kafka:
    cache:
      defaultCacheEntryTimeToLiveMillis: 518400000
      defaultCacheHeapSize: 1000000
spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: fint-skjema-data-service
server:
  port: 8081
logging:
  level:
    no.fintlabs.kafka.consumer.cache: WARN