fint:
  org-id: fintlabs.no
spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: group_id
server:
  port: 8081
logging:
  level:
    no.fintlabs.kafka.consumer.cache: WARN