fint:
  application-id: fint-flyt-data-service
  cache:
    defaultCacheEntryTimeToLiveMillis: 518400000
    defaultCacheHeapSize: 1000000
logging:
  level:
    no.fintlabs.cache.ehcache.FintEhCacheEventLogger: WARN
server:
  max-http-header-size: 40KB
spring:
  profiles:
    include:
      - flyt-kafka
      - flyt-logging
      - flyt-resource-server