fint:
  org-id: fintlabs.no
  cache:
    defaultCacheEntryTimeToLiveMillis: 518400000
    defaultCacheHeapSize: 1000000
  flyt:
    resource-server:
      security:
        api:
          external:
            enabled: true
            authorized-client-ids: 1
          internal:
            enabled: true
            authorized-org-ids:
              - viken.no
              - vigo.no
  kafka:
    topic:
      org-id: ${fint.org-id}
      domain-context: flyt
    application-id: fint-flyt-data-service
spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: fint-flyt-data-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
server:
  port: 8080
  max-http-header-size: 40KB
logging:
  level:
    no.fintlabs.cache.ehcache.FintEhCacheEventLogger: WARN