fint:
  org-id: fintlabs.no
  flyt:
    resource-server:
      security:
        api:
          internal:
            enabled: true
            authorized-org-id-role-pairs-json: "{\"vigo.no\":[\"https://role-catalog.vigoiks.no/vigo/flyt/developer\"]}"
  kafka:
    default-replicas: 1
spring:
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 8085